### ISSUE TITLE
Crash on free() in AROS i386

### ISSUE THREAD

**Issue by mattrust** [sodero/InstallerLG#42]
Hi,

I'm trying to bring InstallerLG v40 into AROS core. It crashes in arg_done:

#4  0xd97ae6c4 in free (memory=0xd9fb06e7) at /home/mazze/projects/fullaros/aros-src/compiler/stdc/./free.c:62
#5  0xd9ff2e9e in arg_done ()
    at /home/mazze/projects/fullaros/aros-linux-i386-dbg/bin/linux-i386/Ports/installerlg/alpha.40/sodero-InstallerLG-07832d6/src/args.c:286
#6  0xd9fdb018 in main (argc=0, argv=0xd9c500a0) at ../src/lexer.l:298

(gdb) p args
$25 = {0x0, 0x0, 0xd9fb06e7 "", 0x0, 0x0, 0x0, 0xda023e40 "System:Utilities", 0x0, 0x0, 0x0}
(gdb) p args[arg]
$26 = 0xd9fb06e7 ""

**Comment by sodero** [comment]
Hi,

I'll try to reproduce this. The 'args' above look a bit strange. Did you start Installer as a tool from WB without a SCRIPT tooltype set?

**Comment by mattrust** [comment]
I did just a double click on Utilities/Installer

**Comment by sodero** [comment]
Ok, thanks! I'll look Into it.

Den tis 31 dec. 2019 16:36mattrust <notifications@github.com> skrev:

**Comment by sodero** [comment]
I couldn't reproduce the crash using the latest version, but I can clearly see that it doesn't work as it should when just double clicking on the tool like you did, when doing so it tries to interpret itself as an installer script :-(

I fixed this behaviour and hopefully this is the same problem that caused a crash on your side?

**Comment by mattrust** [comment]
Still crashing.

(gdb) p args
$19 = {0x0, 0x0, 0xf544ae37 "\365= AVERAGE", 0x0, 0x0, 0x0, 0xf53d1660 "System:Utilities", 0x0, 0x0, 0x0}
(gdb) p args[arg]
$20 = 0xf544ae37 "\365= AVERAGE"

Here are the Tooltypes of the Installer Icon:

![Bildschirmfoto von 2020-01-02 13-43-02](https://user-images.githubusercontent.com/18250926/71667554-eaa74900-2d65-11ea-814a-dc71ccf50aa8.png)

**Comment by sodero** [comment]
Ok, I think I found it. 

Fixed in 3e677bdf87ce7f66c87b146d92d107a2cbc0ddef

**Comment by sodero** [comment]
What are you using to test BTW? Linux hosted i386? ABI_V1?

**Comment by mattrust** [comment]
Yes. I've built it with --enable-debug=all

**Comment by sodero** [comment]
Ok, good to know. My setup (Icaros desktop in a VM) doesn't crash as often as it should, obviously :)
